FROM python:3.13-slim

WORKDIR /app

RUN pip install uv
COPY pyproject.toml uv.lock ./

RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --system .

COPY src/ ./src/
RUN uv pip install --system .

CMD [ "workload_model" ]